### GET request
@baseUrl = http://localhost:3000
GET {{baseUrl}}/employees/

###
GET {{baseUrl}}/employees/7355a654b62c687f97eb

###
POST {{baseUrl}}/employees/
Content-Type: application/json

{
  "name": "John",
  "position": "Manager55",
  "salary": 50000,
  "other": "stuff"
}

###