### GET request
@baseUrl = http://localhost:3000
GET {{baseUrl}}/employees/

###
GET {{baseUrl}}/reports/salaries/

###
GET {{baseUrl}}/employees/7355a654b62c687f97eb

###
POST {{baseUrl}}/employees/
Content-Type: application/json

{
  "name": "Mary",
  "position": "HR",
  "salary": 70000
}

###